config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about' #get method with 2 parameters. controller#action
  resources :pages #resources :nameOfController
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id]) #shows one page by id
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find(params[:id])
    render :form
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to page_path(@page)
    else
      render :form
    end
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to page_path(@page)
    else
      render :form
    end
  end

  def destroy
    Page.find(params[:id]).destroy
    redirect_to pages_path
  end

  private
    def page_params
      params.require(:page).permit(:title, :body, :author)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Pages', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/form.html.erb
<h1>
  <%= @page.id ? 'Edit Page' : 'Add Page' %>
</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />
  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>Pages</h1>
<p>
  <%= link_to 'New Page', new_page_path %>
</p>
<% @pages.each do |page| %>
  <h2><%= page.title %></h2>
  <%= link_to 'Show', page_path(page) %>
<% end %>

app/views/pages/new.html.erb
<h1>Add A Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />
  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<h4><%= @page.author %></h4>
<p><%= @page.body %></p>
<hr />
<%= link_to 'Edit Page', edit_page_path(@page) %>
<%= link_to 'Delete Page', @page, method: :delete %>
<%= link_to 'Back', pages_path %>